### ISSUE TITLE
Compatibility issue with Java 17

### ISSUE THREAD

**Issue by kartikterralogic** [irgaly/android-remove-unused-resources-plugin#135]

**Comment by irgaly** [comment]
I tried this plugin v2.2.0 with JDK 17, command is `JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home ./gradlew :app:removeUnusedResourcesDebug`, then no error was happened.

Please give that things:

* What JDK you use.
* What command you'd run.
* What error happen.
