### ISSUE TITLE
can you adapter this plugin for AGP 4.0+?

### ISSUE THREAD

**Issue by ZHOUJJIN** [irgaly/android-remove-unused-resources-plugin#60]

**Comment by irgaly** [comment]
Thank you for your interest to this plugin!

The latest version of this plugin is v1.3.2 now. This version still supports from AGP 4.0.0 as described in [Readme.md](https://github.com/irgaly/android-remove-unused-resources-plugin#requires).

It's recommended to use AGP 7.0 or higher in your project. I also plan this plugin to support only AGP 7.0.0 and higher with PR #12.
