### ISSUE TITLE
Modified XML tags missing closing angle brackets

### ISSUE THREAD

**Issue by mennahmostafa** [irgaly/android-remove-unused-resources-plugin#72]
When running the plugin V1.3.3 on an android project using Dolphin | 2021.3.1 Patch 1 with a project containing two flavors, I get modifications in some resources where the enclosing <resources> tag is missing the last character `>`. 
To get around it, I move the resource inside this file to another one and I probably get a successful round. 
Any fix?

**Comment by irgaly** [comment]
Thanks for reporting an Issue!
I have not facing that problem.

* What AGP version you use?
* Can you show the resouce file that reproduce the issue?
* Does the issue happens before (with old AGP version or old Android Studio version)?
