### ISSUE TITLE
Add support for groovy build gradle

### ISSUE THREAD

**Issue by TheRemakerMan** [irgaly/android-remove-unused-resources-plugin#95]
I can't add this plugin into ```build.gradle``` file.

**Comment by irgaly** [comment]
What error happen when you apply to groovy build.gradle?


Kotlin DSL become default for Gradle, so I recommend to use build.gradle.kts.

https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds

**Comment by TheRemakerMan** [comment]
Error log: ```
> Could not resolve io.github.irgaly.remove-unused-resources:plugin:1.4.1.
     Required by:
         project :
      > No matching variant of io.github.irgaly.remove-unused-resources:plugin:1.4.1 was found. The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.5.1'
```

Can you make also template for ```build.gradle```? Because some still use ```build.gradle``` not ```build.gradle.kts```.

**Comment by irgaly** [comment]
You can use groovy build.gradle:

```
plugins {
    id 'io.github.irgaly.remove-unused-resources' version '1.4.1'
}
```

document: https://docs.gradle.org/current/userguide/plugins.html

---

It seems your project uses incompatible version of some tool.
What version do you use?

* Gradle Version
* AGP Version
* JVM Version (to run gradle process)

Maybe, you should use JVM 11 for gradle.

**Comment by TheRemakerMan** [comment]
JavaVersion: 17
Kotlin JVM Target: 11
Gradle Version: 7.5.1
AGP Version: 7.4.9

**Comment by TheRemakerMan** [comment]
- JavaVersion: 17
- Kotlin JVM Target: 11
- Gradle Version: 7.5.1
- AGP Version: 7.4.9

**Comment by TheRemakerMan** [comment]
Problem still the same. Please make an example for `build.gradle`.

**Comment by irgaly** [comment]
OK. I made groovy build.gradle sample.

Please see `sample2` project here.

https://github.com/irgaly/android-remove-unused-resources-plugin/tree/445e3a25b0ce53463f50943bad1ed6b06472395a/sample2

---

I have make this project with these steps:

* Create new `Empty Project` from Android Studio HedgeHog Canary 10

> Android Studio Hedgehog | 2023.1.1 Canary 10
> Build #AI-231.9011.34.2311.10366083, built on June 23, 2023
> Runtime version: 17.0.7+0-17.0.7b829.16-10353782 aarch64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 13.4

* Specify versions: Gradle 7.5.1, AGP 7.4.0, jvmTarget=11

![image](https://github.com/irgaly/android-remove-unused-resources-plugin/assets/1311446/307ff41f-c2f5-4842-9aa4-cdbe83b8694b)

![image](https://github.com/irgaly/android-remove-unused-resources-plugin/assets/1311446/8b3343a4-c578-418f-a900-b44ff5ffaead)

![image](https://github.com/irgaly/android-remove-unused-resources-plugin/assets/1311446/e1985e89-cfa1-4796-8a5f-267a98716cb6)

* add this plugin to `app/build.gradle`

https://github.com/irgaly/android-remove-unused-resources-plugin/blob/445e3a25b0ce53463f50943bad1ed6b06472395a/sample2/app/build.gradle#L1-L5

![image](https://github.com/irgaly/android-remove-unused-resources-plugin/assets/1311446/20efc368-6781-4bdc-bf9d-d41cd7135df0)

---

With this sample2 project, I can run these Gradle Tasks (in Android Studio Gradle Run):

* `./gradlew :app:lintDebug`

![image](https://github.com/irgaly/android-remove-unused-resources-plugin/assets/1311446/acc899ac-6c2c-4cbf-ac34-77935a2970f4)

* `./gradlew :app:removeUnusedResources -Prur.lintVariant="debug"`

![image](https://github.com/irgaly/android-remove-unused-resources-plugin/assets/1311446/c01f8b79-d11e-44a6-8ae9-24a12871639c)

**Comment by irgaly** [comment]
Note:

This oringinal error `No matching variant of io.github.irgaly.remove-unused-resources:plugin:1.4.1 was found. ` is occurred if you use JVM 11 to run gradle.
Please use JVM 17 to run gradle.

I made clear that this plugin needs JVM 17 on README.md https://github.com/irgaly/android-remove-unused-resources-plugin#troubleshoots

**Comment by TheRemakerMan** [comment]
> Note:
> 
> This oringinal error `No matching variant of io.github.irgaly.remove-unused-resources:plugin:1.4.1 was found. ` is occurred if you use JVM 11 to run gradle.
> Please use JVM 17 to run gradle.
> 
> I made clear that this plugin needs JVM 17 on README.md https://github.com/irgaly/android-remove-unused-resources-plugin#troubleshoots

Okay.
